# Default application settings, to run the application for local development.
info:
  title: Track My Wealth Ledger Backend Service
  version: 0.1.0
  description: Service to track ledger with double-entry accounting

app:
  debug: true
  show_error_details: true
  cors_origins: "http://localhost:8000,http://localhost:5173"

  # limit for the size of the file that can be uploaded (5MB default)
  import_file_size_limit: 5242880 # bytes

  # serve static files configuration
  static:
    serve_static: false
    static_path: /static

auth:
  x_api_key: "your_api_key_here"

# database settings
db:
  driver: mongodb
  host: localhost
  user: <USER>
  password: <PASSWORD>
  port: 27017
  database: ledger
